os:
- linux
sudo: false
language: python
python:
- "3.6"
install: pip install tox-travis
script: tox

services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER ttt PASSWORD 'tic-tac-toe';" -U postgres
  - psql -c "ALTER USER ttt CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE testdb to ttt;" -U postgres

after_success:
  - coveralls
  - codecov
