version: '2'
services:

  ttt_wg:
    container_name: ttt_local
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep 5 && python manage.py runserver 0.0.0.0:8008 --settings=config.settings"
    volumes:
      - .:/ttt
    ports:
      - "8007:8008"
    links:
    - postgres
    - redis
    stdin_open: true
    tty: true

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - rds:/var/lib/redis/data/
    entrypoint: redis-server --appendonly yes
    restart: always

  postgres:
    container_name: postgres_ttt
    image: postgres
    env_file: ./envs/pg.env
    volumes:
    - pgs:/var/lib/postgresql/data/
    ports:
    - "5431:5432"

volumes:
  pgs:
  rds:
